### ISSUE TITLE
How do I route an item in the menu to another component?

### ISSUE THREAD

**Issue by ghost** [yjose/reactjs-popup-burger-menu#1]
Having a hard time understanding how to go from one route/component to another as a new React dev. Can you elaborate some more on how to use your library? If you can, I can help with docs. They aren't newbie friendly. 

Just need some guidance and if I can help with the docs let me know.

**Comment by yjose** [comment]
Hi  @twhite96 , this repo is a simple repo created by sandboxcode editor , you can find more info here in my article: https://hackernoon.com/create-a-fancy-burger-menu-using-reactjs-popup-e7ed6d3c965f 
if you are talking about [reactjs-popup docs](http://react-popup.netlify.com/) , I will be happy if you have any suggestions on how I can improve the docs content.

**Comment by ghost** [comment]
Thanks but this doesn't answer my question. I'm asking about how to route to another component using this popup. I have a `Text.js` component and a `Home.js` component. I'd like to route to Text from Home etc, sort of like linking pages in a nav in HTML. 

I'm not sure how you accomplish this. Your documentation website for this library does exactly what I am trying to do. I'm asking how you went about linking pages/components in the menu.

**Comment by yjose** [comment]
@twhite96  , you are using react-router?

**Comment by ghost** [comment]
Yes. Just not sure how you did it in this popup. Have an example?

**Comment by ghost** [comment]
@yjose I'm new to React and I've searched pretty wide for answers on how to use React Router for this to no avail. I've used it in another project. Just not sure how to use it with your menu.

**Comment by yjose** [comment]
Hi, @twhite96 , 
I just create a fork with react-router, https://codesandbox.io/s/lpo41x20kq
 good luck

**Comment by ghost** [comment]
Thanks @yjose. I'll close this now.
